name: Sync Claude Code Commands

on:
  schedule:
    # Run every Sunday at 6 AM UTC (weekly)
    - cron: '0 6 * * 0'
  workflow_dispatch:
    # Allow manual triggering

jobs:
  sync-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run command sync script
        id: sync
        run: |
          # Ensure reports directory exists
          mkdir -p reports

          # Run the sync script and capture output
          npm run sync-commands > sync-output.txt 2>&1

          # Check if changes were detected
          if grep -q "Changes detected" sync-output.txt; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in slash commands"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

          # Show the output
          cat sync-output.txt

      - name: Upload sync report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: command-sync-report-${{ github.run_number }}
          path: reports/
          retention-days: 30
          if-no-files-found: warn

      - name: Create issue if changes detected
        if: steps.sync.outputs.changes == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            // Read the latest report
            const reportFiles = fs.readdirSync('reports/').filter(f => f.endsWith('.md'));
            const latestReport = reportFiles.sort().pop();
            const reportContent = fs.readFileSync(`reports/${latestReport}`, 'utf8');

            // Create issue
            const { data: issue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `[Automated] Claude Code Commands Update Available`,
              body: `## 🤖 Automated Command Sync Report

              The weekly command sync detected changes in Claude Code slash commands.

              **Action Required:** Review and update CC4B with new/changed commands.

              ---

              ${reportContent}

              ---

              **Next Steps:**
              1. Review the missing commands list
              2. Update \`src/sections/CommandsReference.jsx\`
              3. Update \`src/sections/EssentialCommands.jsx\` for important commands
              4. Update \`public/claude-code-guide.md\`
              5. Test the changes locally
              6. Deploy and verify

              **Automation:** This issue was created automatically by the weekly command sync workflow.`,
              labels: ['automation', 'commands', 'documentation']
            });

            console.log(`Created issue #${issue.number}: ${issue.title}`);

      - name: Comment on success
        if: steps.sync.outputs.changes == 'false'
        run: |
          echo "✅ Command sync completed successfully - no changes detected"
          echo "CC4B appears to be up-to-date with all known Claude Code commands"